// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfrivZ0XRM_7YKNNF8KG4eMR2O175RRbk',
    appId: '1:345494829026:web:ab0459c689e108ee6b2bbb',
    messagingSenderId: '345494829026',
    projectId: 'blooddonation-df3b5',
    authDomain: 'blooddonation-df3b5.firebaseapp.com',
    storageBucket: 'blooddonation-df3b5.firebasestorage.app',
    measurementId: 'G-9WVJZCFMB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJwgrnJDv1tzMq9pc_AHtpRdJTaKotQ4',
    appId: '1:345494829026:android:24496e46a8c960f96b2bbb',
    messagingSenderId: '345494829026',
    projectId: 'blooddonation-df3b5',
    storageBucket: 'blooddonation-df3b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJMc2y7c3GnhW7u3SFPqkhuov-nrCQK0',
    appId: '1:345494829026:ios:7d54a74dfad774776b2bbb',
    messagingSenderId: '345494829026',
    projectId: 'blooddonation-df3b5',
    storageBucket: 'blooddonation-df3b5.firebasestorage.app',
    iosBundleId: 'com.example.bloodApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJMc2y7c3GnhW7u3SFPqkhuov-nrCQK0',
    appId: '1:345494829026:ios:7d54a74dfad774776b2bbb',
    messagingSenderId: '345494829026',
    projectId: 'blooddonation-df3b5',
    storageBucket: 'blooddonation-df3b5.firebasestorage.app',
    iosBundleId: 'com.example.bloodApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfrivZ0XRM_7YKNNF8KG4eMR2O175RRbk',
    appId: '1:345494829026:web:122f6d7752b2d11d6b2bbb',
    messagingSenderId: '345494829026',
    projectId: 'blooddonation-df3b5',
    authDomain: 'blooddonation-df3b5.firebaseapp.com',
    storageBucket: 'blooddonation-df3b5.firebasestorage.app',
    measurementId: 'G-JX0WMWZRT9',
  );
}
